# Generated by Django 4.0.4 on 2022-05-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('cert_image', models.CharField(max_length=100)),
            ],
        ),
    ]
